- name: install httpd
  yum:
    name: httpd
    state: latest 
  when: ansible_distribution == "Amazon"

- name: Update apt cache and install apache2
  apt:
    update_cache: yes
    name: apache2
    state: latest
  when: ansible_distribution == "Ubuntu"
        
- name: "Check wheather app and database are running."
  script: appcheck.sh  
  args:
    executable: /bin/bash
  ignore_errors: true
  register: app_process_check
- debug: var=app_process_check.stdout             

- name: Check and start patching on Linux servers
  fail:
    msg: "{{ ansible_hostname }} has a running application. Please stop the application and then proceed with the patch."
  when: app_process_check.stdout.strip() == "Process is running."