- name: install httpd
  yum:
    name: httpd
    state: latest 
  when: ansible_distribution == "Amazon"

- name: Update apt cache and install apache2
  apt:
    update_cache: yes
    name: apache2
    state: latest
  when: ansible_distribution == "Ubuntu"
        
             